### ISSUE TITLE
Snap doesn't launch

### ISSUE THREAD

**Issue by pizzadude** [scratux/scratux#1]
Hi, the snap doesn't launch. Here's the error message from the terminal:

scratux
[10372:0430/203519.110318:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /snap/scratux/1/chrome-sandbox is owned by root and has mode 4755.
fish: “scratux” terminated by signal SIGTRAP (Trace or breakpoint trap)

**Comment by joancipria** [comment]
Hi @pizzadude, thank you for the report. I will take it a look tomorrow. Wich distro are you running?

**Comment by pizzadude** [comment]
@joancipria Linux Mint 19.1 (Ubuntu 18.04 based)

**Comment by joancipria** [comment]
It looks like [this](https://github.com/electron/electron/issues/17972) could be the cause of the problem (and also the solution). I'm trying to solve it on develop branch through an [afterpack script](https://www.electron.build/configuration/configuration#afterpack). Until then, I will no publish Snap binaries.

**Comment by pizzadude** [comment]
Okay, thanks for looking into it. :)

**Comment by vladimiry** [comment]
Even if `chrome-sandbox` binary has 4755 permission the Snap still won't start, see details here https://github.com/vladimiry/ElectronMail/issues/134#issuecomment-487960548. Adding `{ "browser-sandbox": { "interface": "browser-support", "allow-sandbox": true }}` to electron-builder config for `snap` target might be a solution, have not tried it yet.

**Comment by pizzadude** [comment]
I used the AppImage for now.

**Comment by joancipria** [comment]
> Even if `chrome-sandbox` binary has 4755 permission the Snap still won't start, see details here [vladimiry/ElectronMail#134 (comment)](https://github.com/vladimiry/ElectronMail/issues/134#issuecomment-487960548). Adding `{ "browser-sandbox": { "interface": "browser-support", "allow-sandbox": true }}` to electron-builder config for `snap` target might be a solution, have not tried it yet.

Thanks @vladimiry , I will try your solution this afternoon. I tried with the afterpack permission script but as you said, it is not working.

**Comment by vladimiry** [comment]
> it is not working.

Setting 4755 permission via `afterpack` script is in general working for the packages like deb/pacman. But the workaround is not sufficient for the Snap package.

**Comment by joancipria** [comment]
@pizzadude Since Scratux is now based on Scratch Desktop it builds in the same way as the official [scratch-desktop](https://github.com/LLK/scratch-desktop), generating working snap binaries. Thank you so much @vladimiry for your help, I'm very keen on this issue so I will be following the ElectronMail one. Thank you again.
