### ISSUE TITLE
Audio for Microphone not working

### ISSUE THREAD

**Issue by shadowbq** [scratux/scratux#11]
The audio recording feature is not working in 1.2 snap version. 

The camera snap fix does work, it just doesnt work with the sound recorder in scatux

Likely related to snap plug.

https://github.com/scratux/scratux/issues/5

**Comment by joancipria** [comment]
Hi! First of all thanks you so much for reporting and sorry for the late response. You are right, it is the same case as #5 and will I will fix it in Scratux 1.3 (wich beta release will be available within next week).

**Comment by joancipria** [comment]
I've just pushed the [interface fix](https://github.com/scratux/scratux-desktop/commit/ef310773c4db52ddd20ba97c65fc648191d670b6). Closing issue.
