### ISSUE TITLE
Error Building on Linux Mint 19.2

### ISSUE THREAD

**Issue by rjmoses** [scratux/scratux#12]
build.sh failed when building on Linux Mint 19.2 with:  (Any suggestions would be appreciated) 

-----------------------------------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dist' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle scratux@1.2.0~predist: scratux@1.2.0
6 silly lifecycle scratux@1.2.0~predist: no script for predist, continuing
7 info lifecycle scratux@1.2.0~dist: scratux@1.2.0
8 verbose lifecycle scratux@1.2.0~dist: unsafe-perm in lifecycle true
9 verbose lifecycle scratux@1.2.0~dist: PATH: /usr/share/npm/bin/node-gyp-bin:/home/rjmoses/scratux/src/node_modules/.bin:./:/sbin:/bin:/usr/bin:/usr/local/bin
10 verbose lifecycle scratux@1.2.0~dist: CWD: /home/rjmoses/scratux/src
11 silly lifecycle scratux@1.2.0~dist: Args: [ '-c',
11 silly lifecycle   'npm run build-gui && npm run fetch && npm run compile -p && electron-builder' ]
12 silly lifecycle scratux@1.2.0~dist: Returned: code: 1  signal: null
13 info lifecycle scratux@1.2.0~dist: Failed to exec dist script
14 verbose stack Error: scratux@1.2.0 dist: `npm run build-gui && npm run fetch && npm run compile -p && electron-builder`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid scratux@1.2.0
16 verbose cwd /home/rjmoses/scratux/src
17 error Linux 4.15.0-66-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dist"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error scratux@1.2.0 dist: `npm run build-gui && npm run fetch && npm run compile -p && electron-builder`
22 error Exit status 1
23 error Failed at the scratux@1.2.0 dist script 'npm run build-gui && npm run fetch && npm run compile -p && electron-builder'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the scratux package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build-gui && npm run fetch && npm run compile -p && electron-builder
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs scratux
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls scratux
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
---------------------------------------------------------------------------------------------------

**Comment by joancipria** [comment]
Hi! First of all thanks you so much for reporting and sorry for the late response. I've just build it on Linux Mint 19.3 and is working for me. Please update Node to the latest LTS version (v12.16.1) and try again. Let me know if you have any problem.

![Screenshot_2020-02-23_13-44-33](https://user-images.githubusercontent.com/16108809/75112289-a8520800-5642-11ea-845a-4155526933db.png)
