### ISSUE TITLE
Remove Coming Soon links / tools in tool bar (Suggestion)

### ISSUE THREAD

**Issue by redshaderobotics** [scratux/scratux#3]
Is it possible to remove the features after the tutorials menu in menu bar. As the offline editors dont have these functionalities.
Thanks

**Comment by joancipria** [comment]
Hi @redshaderobotics , for sure it would be a good improvement. I will try to remove them in next version. Thank you for the suggestion!

**Comment by joancipria** [comment]
@redshaderobotics since Scratux is now based on Scratch Desktop (instead of the online editor) it is no longer showing  remove and coming soon links. Closing issue
