### ISSUE TITLE
Ubuntu Repository not signed

### ISSUE THREAD

**Issue by malcreatuire** [scratux/scratux#7]
The repository  »https://dl.bintray.com/scratux/stable bionic Release« is not signed anymore. Therefore apt refuses to update or install any packages from the repository.

**Comment by joancipria** [comment]
Hi @malcreatuire and thanks you so much for reporting the issue. I have just refreshed the metadata so now signing should be ok. Please, tell me if it is working for you.

**Comment by malcreatuire** [comment]
it works fine now
