### ISSUE TITLE
scratux-desktop needs translation

### ISSUE THREAD

**Issue by joancipria** [scratux/scratux#8]
Thanks to Albano for reporting the issue. Currently our upstream [scratch-desktop](https://github.com/LLK/scratch-desktop) does not provide translations so all modals are in english. I've decided to provide our own translatons, so now there is a new repo (https://github.com/scratux/scratux-i18n) that collects translations submitted to the Scratux projects on the POEditor platform. **Please do not submit PRs. If you would like to contribute translations, please sign up to translate on POEditor at https://poeditor.com/join/project/ONVBkRVtur**

On the other hand, I'm working on the [unstable branch of scratch-desktop](https://github.com/scratux/scratux-desktop/tree/develop-unstable) to integrate the translation system

**Comment by jolly-jump** [comment]
<del>Can you hint me where to find an english-only modal dialog?
Is this still an open issue?</del>
Ok, found the few translatable strings in the repo files, sorry. It is the "About" dialog and the "stay/leave" dialog whenever you try to close the app.
I <del>would like to</del> provided a german translation.

**Comment by joancipria** [comment]
Thanks you so much for contributing to the project @jolly-jump ! Translations are already working on the [unstable branch of scratch-desktop](https://github.com/scratux/scratux-desktop/tree/develop-unstable) and will be shipped with the next Scratux v1.3 release (which will be available within next week) so I'm closing this issue. If you have any questions please feel free to reopen this issue.
